spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: koicaresystemv3
    url: jdbc:sqlserver://koicaresystemv4.database.windows.net:1433;database=koicaresystem;user=koicaresystemv3@koicaresystemv4;password=Application123@;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    password: Application123@
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: storephuoc@gmail.com
    password: ncux oxqc ldqu leih
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
  cloud:
    azure:
      storage:
        account-name: koicaresystemv4
        account-key: fGdidW7fAzitn903ZOFQ5gasSPcZc+WdZdI47pziK3XMeF8eFjUBnvho1+UpB9dQ3qIzk2y9rZ6d+AStd3gfaQ==
  servlet:
    multipart:
      enabled: true
      max-request-size: 20MB
      max-file-size: 2MB
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 1056246324863-hav4lnp56ue6iadohmo8279laj65iusr.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email
            redirect-uri: "{baseUrl}/login/oauth2/code/google"
          github:
            client-id: Ov23liI6eH4xWtf87p0n
            client-secret: 9044741ccb1757c8a5c91c41c4110c4f09d7e542
            scope: read:user, user:email
            redirect-uri: "{baseUrl}/login/oauth2/code/github"
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
            user-name-attribute: id
