server:
  port: 8080
  servlet:
    multipart:
      enabled: true
      max-request-size: 20MB
      max-file-size: 2MB
    context-path: /api
  error:
    include-message: always

spring:
  profiles:
    active: dev
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false

