server:
  port: 8080
  servlet:
    context-path: /api
  error:
    include-message: always

spring:
  profiles:
    active: dev
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false
    servlet:
      multipart:
        max-file-size: 50MB

