server:
  port: 8080
  servlet:
    context-path: /api
  error:
    include-message: always

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/koi-care-system
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true
jwt:
  signerKey: "UWOG67IDTlxApTrrn3ukTybaTHxvUyCuQ2FjMcTeRclpqNiPe9Yr3Fyt1j8zlvjn"
# cài MySQL với account là username: root với password là admin, xong vào bấm tạo
# 1 cái database tên koi-care-system là chạy được/ tạo database th không cần tạo bảng
