spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    username: koicaresystem@koicaresystem
    url: jdbc:sqlserver://koicaresystem.database.windows.net:1433;database=koi-care-system
    password: Application123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    open-in-view: true
  spring:
    mail:
      host: smtp.gmail.com
      port: 587
      username: storephuoc@gmail.com
      password: ncux oxqc ldqu leih
      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true
            connectiontimeout: 5000
            timeout: 5000
            writetimeout: 5000       #application doesn't wait if the SMTP server takes too long to respond.
